# Generated by Django 2.1.5 on 2020-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200520_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Artist_Description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='lyricist_descrption',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
