# Generated by Django 2.1.5 on 2020-05-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200520_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Trends',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
