# Generated by Django 2.1.5 on 2020-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_trends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='Trends',
        ),
        migrations.AddField(
            model_name='songs',
            name='Trends',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
