# Generated by Django 2.1.5 on 2020-06-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_album_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Artist_logo',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
