# Generated by Django 2.1.5 on 2020-06-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20200610_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(upload_to='blog_images/', verbose_name='Image'),
        ),
    ]
