# Generated by Django 2.1.5 on 2020-06-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20200612_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='blog_images/', verbose_name='Image'),
        ),
    ]
