# Generated by Django 2.1.5 on 2020-06-14 19:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0014_playlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlists',
            new_name='User_Playlists',
        ),
    ]
